CREATE TABLE `tiny_url_category` (
	`id` SMALLINT(6) UNSIGNED NOT NULL AUTO_INCREMENT,
	`name` VARCHAR(255) NOT NULL COMMENT '分类名',
	`project_id` INT(11) UNSIGNED NOT NULL COMMENT '所属项目',
	`status` TINYINT(1) UNSIGNED NOT NULL DEFAULT '1' COMMENT '1：启用，2：删除',
	`add_time` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	PRIMARY KEY (`id`)
)
